DESCRIBE Author;
DESCRIBE Book;

SHOW COLUMNS FROM Book;
DESCRIBE BookAuthor;
DESCRIBE BookCopy;
DESCRIBE User;
DESCRIBE Loan;
DESCRIBE Reservation;
DESCRIBE FineRate;
DESCRIBE Room;
DESCRIBE RoomBooking;
DESCRIBE LoanLog;