ALTER TABLE Author ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE Author ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE Book ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE Book ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE BookAuthor ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE BookAuthor ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE BookCopy ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE BookCopy ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE User ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE User ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE Loan ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE Loan ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE Reservation ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE Reservation ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE FineRate ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE FineRate ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE Room ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE Room ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE RoomBooking ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE RoomBooking ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;

ALTER TABLE LoanLog ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NULL;
ALTER TABLE LoanLog ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL;